import { Noto_Sans_Thai } from "next/font/google";
import './globals.css'


const notosansthai = Noto_Sans_Thai({ subsets: ["latin"] });

export const metadata = {
  title: 'Donmark Thailand',
  description: 'Generated by Ittisak',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notosansthai.className}>

        {children}

        </body>
    </html>
  )
}
